name: publish

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      dragonfly:
        image: "docker.dragonflydb.io/dragonflydb/dragonfly"
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set Up Bun Package Manager
        uses: oven-sh/setup-bun@v2

      - name: Install Project Dependencies
        run: bun install --frozen-lockfile

      - name: Run Test Suite
        env:
          REDIS_SERVICE_URI: redis://localhost:6379
          POSTGRES_SERVICE_URI: postgres://user:password@localhost:5432/testdb
        run: bun run test

  publish:
    name: publish
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set Up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Project Dependencies
        run: bun install --frozen-lockfile

      - name: Build the package
        run: bun run build

      - name: Prepare npm Packages build
        run: |
          mkdir -p dist-npm
          cp -r dist dist-npm/
          cp CHANGELOG.md LICENSE README.md package.json dist-npm/
      - name: Prepare GitHub Packages build
        run: |
          mkdir -p dist-github
          cp -r dist dist-github/
          cp CHANGELOG.md LICENSE README.md dist-github/
          sed 's/"name": "prisma-extension-redis"/"name": "@yxx4c\/prisma-extension-redis"/' package.json > dist-github/package.json

      - name: Create Distribution Archive
        run: |
          mkdir -p dist-archive
          zip -r dist-archive/build.zip dist package.json README.md LICENSE CHANGELOG.md
          tar -czvf dist-archive/build.tar.gz dist package.json README.md LICENSE CHANGELOG.md

      - name: Publish Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: https://registry.npmjs.org
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun run release
